version: "3.8"
services:
###################### API Gateway ################################
    gateway:
        build:
            context: ./api_gateway
        environment:
            USER_SERVICE: http://user:8000
            BOOKING_SERVICE: http://booking:8000
            TRIP_SERVICE: http://trip:8000
            DRIVER_STATE_SERVICE: http://driver-state:8000
            PAYMENT_SERVICE: http://payment:8000
        image: chittalpatel/uber-api-gateway:latest
        ports:
            -   '8000:8000'
        networks:
            - uber

######################### User Service ######################################
    user:
        build:
            context: ./user_management_service
        environment:
            PAYMENT_SERVICE: http://payment:8000
        image: chittalpatel/uber-user-service:latest
        networks:
            - uber

################### Booking Service ##################
    booking:
        build:
            context: ./booking_service
        image: chittalpatel/uber-booking-service:latest
        environment:
            DRIVER_STATE_SERVICE: http://driver-state:8000
        networks:
            - uber

################### Trip Service ##################
    trip:
        build:
            context: ./trip_management_service
        image: chittalpatel/uber-trip-service:latest
        environment:
            PAYMENTS_DOMAIN: http://payment:8000
        networks:
            - uber

################### Driver State Service ##################
    driver-state:
        build:
            context: ./driver_state_service
        image: chittalpatel/uber-driver-state-service:latest
        environment:
            PYTHONUNBUFFERRED: 1
        networks:
            - uber

################### Payment Service ##################
    payment:
        build:
            context: ./payments_service
        image: chittalpatel/uber-payment-service:latest
        environment:
            USER_SERVICE: http://user:8000
            BOOKING_SERVICE: http://booking:8000
        networks:
            - uber

#########################################################################
networks:
    uber: