version: "3.8"
services:
###################### API Gateway ################################
    gateway:
        build:
            context: ./api_gateway
        env_file:
            - gateway-env.list
        image: chittalpatel/uber-api-gateway:latest
        networks:
            - uber

####################### Kafka server ####################################
    zookeeper:
        image: 'bitnami/zookeeper:latest'
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
        networks:
            - uber
        ports:
            - '2181:2181'

    kafka:
        image: 'bitnami/kafka:latest'
        environment:
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
            - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
            - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
            - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
        networks:
            - uber
        ports:
            - '9093:9093'
        depends_on:
            - zookeeper

######################### User Service ######################################
    user:
        build:
            context: ./user_management_service
        environment:
            KAFKA_HOST: kafka
        env_file:
            -   user-env.list
        image: chittalpatel/uber-user-service:latest
        networks:
            - uber
        ports:
            - 8000:8000
        depends_on:
            - kafka

################### Booking Service ##################
    booking:
        build:
            context: ./booking_service
        image: chittalpatel/uber-booking-service:latest
        networks:
            - uber

################### Trip Service ##################
    trip:
        build:
            context: ./trip_management_service
        image: chittalpatel/uber-trip-service:latest
        networks:
            - uber

################### Driver State Service ##################
    driver-state:
        build:
            context: ./driver_state_service
        image: chittalpatel/uber-driver-state-service:latest
        networks:
            - uber

################### Payment Service ##################
    payment:
        build:
            context: ./payments_service
        image: chittalpatel/uber-payment-service:latest
        networks:
            - uber

#########################################################################
networks:
    uber: